server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        # 1. Auth-Service (PUBLIC)
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**

        # 2. Product-Service (PROTECTED)
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter

        # 3. Customer-Service (PROTECTED)
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
          filters:
            - AuthFilter

        # 4. Order-Service (PROTECTED)
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**
          filters:
            - AuthFilter